spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:batch-db;MODE=MySQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  h2:
    console:
      enabled: true
file:
  input:
    sample-data.csv
